# Generated by Django 3.2.4 on 2021-07-09 07:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 9, 8, 41, 19, 320921)),
        ),
    ]
