# Generated by Django 3.2.4 on 2021-07-09 07:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_rename_date_chat_chat_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='chat_date',
        ),
        migrations.AddField(
            model_name='chat',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
