# Generated by Django 3.2.4 on 2021-07-24 00:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0011_connected_channels'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Connected_channels',
            new_name='Connected_channel',
        ),
    ]
