# Generated by Django 3.2.4 on 2021-07-24 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_rename_connected_channels_connected_channel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='connected',
        ),
    ]
