# Generated by Django 3.2.4 on 2021-07-30 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_online'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['date']},
        ),
    ]
